### ISSUE TITLE
How convert the model?

### ISSUE THREAD

**Issue by ZeroCool22** [ratwithacompiler/diffusers_stablediff_conversion#3]
It the correct way?:

` ./convert_diffusers_to_sd.py C:\Users\ZeroCool22\Desktop\Dreambooth\output\unet C:\Users\ZeroCool22\Desktop\Modelos para Stable Diffusion\sd-v1-4.ckpt C:\Users\ZeroCool22\Desktop\Dreambooth\convertido`

**Comment by Jay4242** [comment]
I think you want to point it to the entire \output\ directory.

**Comment by ZeroCool22** [comment]
> I think you want to point it to the entire \output\ directory.

OK, i have like this:

![Screenshot_3](https://user-images.githubusercontent.com/13344308/193612708-5d9be35b-a944-4a0e-b99d-96d16b17528c.jpg)

But, i get this error:

![trtrrrrrrr jpg](https://user-images.githubusercontent.com/13344308/193613700-f33ab038-d098-4dba-b449-349c6c7b354f.png)
